### PR TITLE
fix(ios): modules to support SDK 9.x.x and iOS 10

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-28509

**Summary:**
- Updated bundled modules to include 32-bit libraries and support iOS 10.
- Needed to make modules work with Titanium 9.x.x since their "minsdk" are still set to 9.2.0.

### CODE REVIEW

**Comment by jquick-axway** [comment]
@ewanharris , would you mind testing this PR out on your iPhone 5 please? Simplest thing to do is...
1. Install this PR's Titanium SDK. (Which will install its modules.)
2. Set up "tiapp.xml" to build with Titanium 9.2.0 and this PR's "ti.map" version 5.1.1.
3. Build and run with the below for iPhone 5.

```javascript
const map = require("ti.map");
const annotations = [];
annotations.push(map.createAnnotation({
	userData: { type: "waypoint" },
	bubbleParent: false,
	title: "Hello World",
	latitude: 51.507,
	longitude: 0.128,
}));
const window = Ti.UI.createWindow();
const mapView = map.createView({ width: Ti.UI.FILL, height: Ti.UI.FILL });
mapView.addAnnotations(annotations);
window.add(mapView);
window.addEventListener("open", () => {
	mapView.showAnnotations(annotations);
});
window.open();
```

For the other modules, maybe simply requiring them in will be enough to test loading their libraries?

**Comment by garymathews** [comment]
Another test for Hyperloop is to include a native module and attempt to utilize it

**\<project\>\Podfile**
```
install! 'cocoapods',
    :integrate_targets => false

platform :ios, '8.0'
use_frameworks!
target 'alloyTest' do
    pod 'MTBBarcodeScanner'
end
```

**app.js**
```JS
const MTBBarcodeScanner = require('MTBBarcodeScanner/MTBBarcodeScanner');
```

Project should build correctly, should not see this error:
```
[TRACE] Undefined symbols for architecture i386:
[TRACE]   "_OBJC_CLASS_$_HyperloopPointer", referenced from:
[TRACE]       objc-class-ref in mtbbarcodescanner.o
[TRACE]   "_OBJC_CLASS_$_HyperloopUtils", referenced from:
[TRACE]       objc-class-ref in mtbbarcodescanner.o
[TRACE] ld: symbol(s) not found for architecture i386
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jquick-axway** [comment]
@ewanharris , @garymathews , regarding the hyperloop test, note that I updated the hyperloop module in PR #12905 (I combined it with my iOS LiveView fix).

**Review by ewanharris — APPROVED** [review]
FR pass, able to load the following modules successfully on an iPhone 5 using 9.3.2.GA

* facebook
* ti.coremotion
* ti.webdialog
* ti.identity
* ti.map
* urlSession

Note: I can't test that ti.applesignin loads on the iPhone 5 as it requires iOS 13+
