### PR TITLE
[TIMOB-25749] Android: Fix loading of commonjs modules

### PR DESCRIPTION
**Pull request by garymathews**
- Fix regression caused by https://github.com/appcelerator/titanium_mobile/pull/9694

###### TEST CASE
- Include [com.foo.bar](https://jira.appcelerator.org/secure/attachment/64855/com.foo.bar-android-1.0.0.zip) in a Titanium project
- Build project

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25749)

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
@garymathews , I am getting this different error with the fix.

```
[ERROR] :  Failed to compile Java source files:
[ERROR] :  
[ERROR] :  /Users/lchoudhary/Desktop/workspaces/workspace_2018/TIMOB-25749/build/android/gen/com/app/timob25749/Timob25749Application.java:113: error: cannot find symbol
[ERROR] :  						(Class<KrollSourceCodeProvider>) Class.forName(className));
[ERROR] :  						       ^
[ERROR] :    symbol:   class KrollSourceCodeProvider
[ERROR] :    location: class Timob25749Application
[ERROR] :  Note: Some input files use unchecked or unsafe operations.
[ERROR] :  Note: Recompile with -Xlint:unchecked for details.
[ERROR] :  1 error
[ERROR] Application Installer abnormal process termination. Process exit value was 1
```

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Review by jquick-axway — APPROVED** [review]

**Comment by lokeshchdhry** [comment]
@garymathews , Now I get this error:
```
[ERROR] :  Failed to compile Java source files:
[ERROR] :  
[ERROR] :  /Users/lchoudhary/Desktop/workspaces/workspace_2018/TIMOB-25749/build/android/gen/com/app/timob25749/Timob25749Application.java:11: error: cannot find symbol
[ERROR] :  import org.appcelerator.kroll.KrollSourceCodeProvider;
[ERROR] :                               ^
[ERROR] :    symbol:   class KrollSourceCodeProvider
[ERROR] :    location: package org.appcelerator.kroll
[ERROR] :  /Users/lchoudhary/Desktop/workspaces/workspace_2018/TIMOB-25749/build/android/gen/com/app/timob25749/Timob25749Application.java:114: error: cannot find symbol
[ERROR] :  						(Class<KrollSourceCodeProvider>) Class.forName(className));
[ERROR] :  						       ^
[ERROR] :    symbol:   class KrollSourceCodeProvider
[ERROR] :    location: class Timob25749Application
[ERROR] :  Note: Some input files use unchecked or unsafe operations.
[ERROR] :  Note: Recompile with -Xlint:unchecked for details.
[ERROR] :  2 errors
[ERROR] Application Installer abnormal process termination. Process exit value was 1
```

**Comment by lokeshchdhry** [comment]
FR Passed.

No error seen when using commonjs modules.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.2.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.12
Appc CLI:       7.0.2
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1
